### ISSUE TITLE
NumberFormatException when parsing SPDXID larger than MaxInt

### ISSUE THREAD

**Issue by raleigh04** [spdx/Spdx-Java-Library#103]
When faced with with an SPDXID larger than java's max int, tools-java throws a NumberFormatException:

Example:

   `"SPDXID": "SPDXRef-6996049013223528",`
   
   Throws:
   
   `Error converting: Error converting SPDX file: class java.lang.NumberFormatException For input string: "6996049013223528"`

**Comment by goneall** [comment]
@raleigh04 This will be fixed in the next release.

You should be able to work around this issue by doing a search/replace of `SPDXRef-` with `SPDXRef-x` where x is any non-numeric character.

**Comment by raleigh04** [comment]
Thank you!
