### ISSUE TITLE
What is the value of documentNamespace?

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/Spdx-Java-Library#116]
```
ISerializableModelStore modelStore = new MultiFormatStore(new InMemSpdxStore(), MultiFormatStore.Format.XML);
String documentUri = "some_namespace";
ModelCopyManager copyManager = new ModelCopyManager();

SpdxDocument document = SpdxModelFactory.createSpdxDocument(modelStore, documentUri, copyManager);

document.setSpecVersion(Version.TWO_POINT_THREE_VERSION);
document.setName("SPDX-tool-test");

Checksum sha1Checksum = Checksum.create(modelStore, documentUri, ChecksumAlgorithm.SHA1, "d6a770ba38583ed4bb4525bd96e50461655d2758");
AnyLicenseInfo concludedLicense = LicenseInfoFactory.parseSPDXLicenseString("LGPL-3.0-only");
SpdxFile file = document.createSpdxFile("SPDXRef-somefile", "./foo.txt", concludedLicense,
                List.of(), "Copyright 2022 some guy", sha1Checksum)
        .build();

document.getDocumentDescribes().add(file);

assertThat(modelStore.getValue(documentUri, "SPDXRef-DOCUMENT", "documentNamespace")).isEmpty();

modelStore.serialize(documentUri, new FileOutputStream("output.xml"));

SpdxDocument newDocument = SpdxToolsHelper.deserializeDocument(new File("output.xml"));

assertThat(newDocument.getModelStore().getValue(newDocument.getDocumentUri(), "SPDXRef-DOCUMENT", "documentNamespace").get()).isEqualTo("some_namespace");
```
The code above creates a minimal SpdxDocument, serializes it and then deserializes it again.

Take note of the two assertion statements:
Before serialization, there is no value named `documentNamespace` saved in the modelStore.
After deserialization, the value has been set to that of the `documentUri`.

Thus, one of the procedures -- either generating a document from scratch or deserializing an existing one -- seems to be buggy. This also raises the question of why the `documentNamespace` property is desirable in the first place, as it seems to simply mirror the `documentUri`.

This issue is probably related to https://github.com/spdx/spdx-java-tagvalue-store/issues/26

**Comment by armintaenzertng** [comment]
I suggest adding `SpdxConstants.PROP_DOCUMENT_NAMESPACE` to `SKIPPED_PROPERTIES` [here](https://github.com/spdx/spdx-java-jackson-store/blob/3e101f12f5292d2edd36a4bd4ccc1e3f300e66fc/src/main/java/org/spdx/jacksonstore/JacksonDeSerializer.java#L69)

This way it will get ignored [here](https://github.com/spdx/spdx-java-jackson-store/blob/3e101f12f5292d2edd36a4bd4ccc1e3f300e66fc/src/main/java/org/spdx/jacksonstore/JacksonDeSerializer.java#L321) and no value with name `"documentNamespace"` will be added to the document

**Comment by goneall** [comment]
> thus, one of the procedures -- either generating a document from scratch or deserializing an existing one -- seems to be buggy.

Agree

> This also raises the question of why the documentNamespace property is desirable in the first place, as it seems to simply mirror the documentUri.

These are the same - the reason for the `documentNamespace` in the serialized document is to have a place to store it even though it is not technically a property of the document itself.  This isn't needed in some formats, like RDF, which natively support namespaces.

> I suggest adding SpdxConstants.PROP_DOCUMENT_NAMESPACE to SKIPPED_PROPERTIES

That does look like a good solution.

@armintaenzertng - did you want to do a pull request and see if it passes all the unit tests with this change?

**Comment by armintaenzertng** [comment]
all right, I will do that tomorrow! :)

**Comment by armintaenzertng** [comment]
I just tested it locally, the issue is resolved :)
