### ISSUE TITLE
No crossRef on an extractedLicenseInfo?

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/Spdx-Java-Library#120]
According to [spec](https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/#104-license-cross-reference-field), an `extractedLicenseInfo` has the property LicenseCrossReference  which I assumed to be implemented by the class [CrossRef](https://github.com/spdx/Spdx-Java-Library/blob/06ffee5e3754400a36dbb2f652d814c92e228e87/src/main/java/org/spdx/library/model/license/CrossRef.java).
`extractedLicenseInfo` has no setter for a `CrossRef` object, though, only for a string collection `seeAlso`. Which for current purposes is totally fine as the intent to provide a URL is still taken care of. I just wondered if `seeAlso` should actually be a (collection of) `CrossRef`s

**Comment by goneall** [comment]
@armintaenzertng - the `seeAlso` collection maps directly to the tag LicenseCrossReference.

`CrossRef` is actually for a different purpose.  It is used to record more detail about the the URL's listed in the Listed Licenses web page (e.g. if they are live).  It should only be used for listed licenses today.

There is an issue in the spec repo to document these fields: https://github.com/spdx/spdx-spec/issues/46

For the purposes of `extractedLicenseInfo` I suggest just using the `seeAlso` collection.

**Comment by armintaenzertng** [comment]
ok then, if `seeAlso` is fine, I just got confused due to the different naming conventions in the spec and the code.

Thanks for clarifying! :)
