### ISSUE TITLE
License information in file should not be mandatory

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/Spdx-Java-Library#130]
According to [spec](https://spdx.github.io/spdx-spec/v2.3/file-information/#86-license-information-in-file-field), the field "License information in file" can be omitted.
This clashes with [the SpdxFileBuilder](https://github.com/spdx/Spdx-Java-Library/blob/master/src/main/java/org/spdx/library/model/SpdxFile.java#L372) where `licenseInfosFromFile` is required to be non-null.

**Comment by goneall** [comment]
@armintaenzertng Good catch - I probably missed this update when updating for the SPDX 2.3 spec update.
