### ISSUE TITLE
Add standard exception equivalents of LicenseCompareHelper.isStandardLicenseWithinText​ and LicenseCompareHelper.matchingStandardLicenseIds​

### ISSUE THREAD

**Issue by pmonks** [spdx/Spdx-Java-Library#152]
It would be great if there were standard exception equivalents of [LicenseCompareHelper.isStandardLicenseWithinText](https://github.com/spdx/Spdx-Java-Library/blob/master/src/main/java/org/spdx/utility/compare/LicenseCompareHelper.java#L852) and [LicenseCompareHelper.matchingStandardLicenseIds](https://github.com/spdx/Spdx-Java-Library/blob/master/src/main/java/org/spdx/utility/compare/LicenseCompareHelper.java#L911).

**Comment by pmonks** [comment]
Notes:
* This was an oversight in PR #145 
* I'll start working on this now, and submit a PR for review soon (and please note it will need extra attention, as my Java is **very** rusty!)

**Comment by goneall** [comment]
Fixed with PR #154
