### ISSUE TITLE
equivalent function may not be threadsafe

### ISSUE THREAD

**Issue by goneall** [spdx/Spdx-Java-Library#168]
`ModelObject.equivalent` does do any locks before retrieving the list of properties and comparing properties.

We could wrap it in a critical section, but if an equivalent is called on the other object (e.g. reverse the order of ModelObject parameters), it will cause a deadlock.

We may be able to just use synchronized methods.

**Comment by pmonks** [comment]
Note that with the advent of Project Loom, the `synchronized` keyword is no longer recommended, since it ties up a "carrier thread" (a physical OS thread) when synchronization happens.

**Comment by goneall** [comment]
Good point @pmonks.  We could create a high (course) level lock for all equivalent functions.  This would ensure the lock hierarchy.

**Comment by goneall** [comment]
I did a more careful review of the code and came to the conclusion it is thread safe.

There is a window between collecting all the property names and comparing the actual properties.  However, if the property goes away during that window, it will just show up as empty in `Optional` which will fail the compare.  Since the object is changing during the equivalent call, I would think having it return false would be expected.
