### ISSUE TITLE
Redundant warning for spdxDocument field

### ISSUE THREAD

**Issue by Badya** [spdx/Spdx-Java-Library#177]
When generating `externalDocumentRefs` for libraries that have `spdx.json` it links `spdxDocument` to library's `documentNamespace` and emits warnings which and not very informative.

```
[WARNING] URI https://www.jetbrains.com/spdxdocs/bb7ae940-90ba-49fe-af02-0e3f6cee30ab does not match any model object or enumeration
```

According to `documentNamespace` field [docs](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#652-intent) 
> NOTE: The URI does not have to be accessible. It is only intended to provide a unique ID. In many cases, the URI will point to a Web accessible document, but this should not be assumed to be the case.

I'd suggest replacing warning with debug or adding a separate handling clause for `spdxDocument` [here](https://github.com/spdx/Spdx-Java-Library/blob/182ffa677e65a1dd315fc5269ed21812dda3fccd/src/main/java/org/spdx/library/model/SimpleUriValue.java#L112)

**Comment by goneall** [comment]
Thanks @Badya for reporting this.  I've also seen this warning but wasn't sure what generated it.  I agree it should be fixed.

Do you happen to have an example JSON file that produces the warning?  I think we should just handle the `spdxDocument`, but I want to make sure I fully understand when this warning is generated.

**Comment by Badya** [comment]
```
{
  "SPDXID" : "SPDXRef-DOCUMENT",
  "spdxVersion" : "SPDX-2.3",
  "creationInfo" : {
    "created" : "2023-06-05T14:26:55Z",
    "creators" : [ "Organization: JetBrains s.r.o.", "Tool: spdx-maven-plugin" ],
    "licenseListVersion" : "3.20"
  },
  "name" : "kotlin-maven-plugin",
  "dataLicense" : "CC0-1.0",
  "externalDocumentRefs" : [ {
    "externalDocumentId" : "DocumentRef-org.jetbrains.kotlinkotlin-stdlib-jdk71.9.255-SNAPSHOT",
    "checksum" : {
      "algorithm" : "SHA1",
      "checksumValue" : "ff70a9cdaa2b71a95811b81a0c653dbe1b19fe73"
    },
    "spdxDocument" : "https://www.jetbrains.com/spdxdocs/1c09e207-81c2-429c-938f-8d175904b904"
  }]
  }
```
This is the minified version of the resulting JSON with other components omitted.
