### ISSUE TITLE
IO Exception: missing JSON for OFL-1.0-no-RFN

### ISSUE THREAD

**Issue by pmonks** [spdx/Spdx-Java-Library#181]
Just today I started getting this exception from the library:
```
17:44:13.904 [main] ERROR org.spdx.library.model.license.SpdxListedLicenseException: I/O Error reading license data for ID OFL-1.0-no-RFN
    org.spdx.storage.listedlicense.SpdxListedLicenseModelStore.fetchLicenseJson (SpdxListedLicenseModelStore.java:333)
    org.spdx.storage.listedlicense.SpdxListedLicenseModelStore.setValue (SpdxListedLicenseModelStore.java:455)
    org.spdx.library.model.ModelObject.setPropertyValue (ModelObject.java:386)
    org.spdx.library.model.ModelObject.setPropertyValue (ModelObject.java:401)
    org.spdx.library.model.license.SimpleLicensingInfo.<init> (SimpleLicensingInfo.java:69)
    org.spdx.library.model.license.License.<init> (License.java:78)
    org.spdx.library.model.license.SpdxListedLicense.<init> (SpdxListedLicense.java:71)
    org.spdx.library.model.SpdxModelFactory.getModelObject (SpdxModelFactory.java:202)
    org.spdx.library.model.SpdxModelFactory.createModelObject (SpdxModelFactory.java:175)
    org.spdx.library.model.license.ListedLicenses.getListedLicenseById (ListedLicenses.java:192)

    ...stack trace from my code omitted...
```

I wasn't sure if this was really an issue with Spdx-Java-Library or something else (and if so, what precisely).

This is coming from v1.1.7 of the library, running on JVM `OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)`.

**Comment by goneall** [comment]
Interesting ... I just tried to access the same license data and it worked.  I wonder if there may be a temporary internet issue.  You may want to try again and see if it reproduces in an hour or so.

**Comment by pmonks** [comment]
Just out of interest, where is this data pulled from?  I had some weird issues earlier accessing github.com, and you now have me wondering if I have some kind of weird internet problem at my end.

**Comment by pmonks** [comment]
Update: it's working now, so I'm going to chalk this up to a connectivity gremlin on my end. Sorry for wasting your time!

**Comment by goneall** [comment]
> Just out of interest, where is this data pulled from? I had some weird issues earlier accessing github.com, and you now have me wondering if I have some kind of weird internet problem at my end.

https://spdx.org/licenses/licenses.json for the table of contents and https://spdx.org/licenses/[license-id].json for the details (where `[license-id]` is the license ID.
