### ISSUE TITLE
Need to update optional fields handling for cases with filesAnalyzed=true

### ISSUE THREAD

**Issue by AlexanderYukhanov** [spdx/Spdx-Java-Library#197]
Starting with 2.2.2 the following fields are optional even if filesAnalyzed are true:
- https://spdx.github.io/spdx-spec/v2.2.2/package-information/#79-package-verification-code-field
- https://spdx.github.io/spdx-spec/v2.3/package-information/#714-all-licenses-information-from-files-field
- package files.

Today the library generate incorrect errors if those fields are omitted (e.g. 
https://github.com/spdx/Spdx-Java-Library/blob/master/src/main/java/org/spdx/library/model/SpdxPackage.java#L631)

**Comment by AlexanderYukhanov** [comment]
Submitted https://github.com/spdx/Spdx-Java-Library/pull/198 to fix it

**Comment by goneall** [comment]
Fixed with PR #198
