### ISSUE TITLE
Do we have a release schedule?

### ISSUE THREAD

**Issue by AlexanderYukhanov** [spdx/Spdx-Java-Library#201]
It would be helpful to know when is the next release coming.

**Comment by goneall** [comment]
We've typically done releases "on request" - typically within 2 to 4 weeks of a request.

With OSS Summit Europe coming up, it will probably be about 3 weeks or so to spin a complete release of all the SPDX java tools - but I could spin just a release of the Java tools this week if it is needed.

Should we plan on a release in 3 weeks (or sooner if just the Java library)?

**Comment by AlexanderYukhanov** [comment]
It would be really helpful if we could release the library first.

**Comment by goneall** [comment]
I'm going to see if we can get one more PR merged before release - likely mid to late next week.  I'll release just the library so we don't have to wait for the other library PR's/issues.

**Comment by goneall** [comment]
@AlexanderYukhanov - I just release version 1.1.8.  It may take a couple hours before Maven Central is updated with the release.
