### ISSUE TITLE
LicenseCompareHelper: BSD-2-Clause license text not recognised

### ISSUE THREAD

**Issue by pmonks** [spdx/Spdx-Java-Library#214]
The following `BSD-2-Clause` license text is not being recognised by `org.spdx.utility.compare.LicenseCompareHelper.isStandardLicenseWithinText()`.

Note: tested with Spdx-Java-Library v1.1.8.

```text
BSD 2-Clause License

Copyright (c) 2023, Peter Monks

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

Note: I have a sneaking suspicion (without any evidence) that this issue, along with #213, #184, and #182 might all be symptoms of the same issue with template-based matching.  I'm still capturing more examples as I find them though, as that gives us more test cases to make sure it's fully fixed.

**Comment by goneall** [comment]
@pmonks thanks for collecting the issues.  I'm going to be traveling for 3 weeks, so it may be a while before I can research the issues.

**Comment by pmonks** [comment]
Absolutely no problem! I may be able to take a closer look in the coming weeks myself (not that I really know that code very well yet) - I'm just wrapping up a decent chunk of work, so it's a good time to start looking at something else.
