### ISSUE TITLE
Refactor nonOptionalTextToPatterns

### ISSUE THREAD

**Issue by goneall** [spdx/Spdx-Java-Library#222]
After PR #221, the method `nonOptionalTextToPatterns` in `LicenseCompareHelper` has a complexity of 89 which is far to high.

I wasn't able to come up with a clean way to refactor the method into several static methods.

There are a couple alternative approaches:

- Create a separate non-static class to parse the license templates and create the patterns
- Change the FilterTemplateOutputHandler to output the actual regex for the license - e.g. construct the regex as the template is being filtered and create 2 methods `getStartRegex(int numWords)` and `getEndRegex(int numWords)`

**Comment by pmonks** [comment]
The first option (separate class dedicated to converting license templates and/or fragments of license templates into regexes) seems like a good option to me.  It might be useful to someone independent of the LicenseCompareHelper, and is probably a lot easier to test too.

**Comment by goneall** [comment]
Fixed with PR #224
