### ISSUE TITLE
Warning message for License list version

### ISSUE THREAD

**Issue by aherbert** [spdx/Spdx-Java-Library#247]
The `spdx-maven-plugin` always outputs this message when using the default configuration (i.e. no license list version information is provided):
```
License list version does not match the pattern M.N
```
I traced this to the `spdx-java-library` by changing the error message in `SpdxCreatorInformation` to:
```java
return "License list version does not match the pattern M.N: " + version;
```
The error is now:
```
License list version does not match the pattern M.N: 3.24.0
```
So the bug is in the use of `matches` instead of `find` as it is trying to match the partial regex `"^[a-zA-Z0-9]+\\.[a-zA-Z0-9]+"` to the **entire** char sequence here:
```java
SpdxConstants.LICENSE_LIST_VERSION_PATTERN.matcher(version).matches()
```
When changed to:
```java
SpdxConstants.LICENSE_LIST_VERSION_PATTERN.matcher(version).find()
```
I see no warning output.

**Comment by garydgregory** [comment]
I can verify that this bug affects building the component jars of the [Apache Commons](https://commons.apache.org/) project.

**Comment by goneall** [comment]
Thanks @garydgregory for the analysis - is the issue that the string in the license list version contains extra characters (e.g. spaces)?  If so, perhaps we can fix this in the spdx-maven-plugin by trimming the string.

From a strict spec perspective, the license list version field should match precisely.

**Comment by aherbert** [comment]
The string is `"3.4.0"`. This is not set within our maven hierarchy (IIUC) so I was assuming it was a default brought in from the SPDX plugin.

The regex is only matching the first two digit fields: `"^[a-zA-Z0-9]+\\.[a-zA-Z0-9]+`, but requires a match to the entire string. This is why changing from `matches` to `find` works. However you can then get junk version numbers like `3.4.whatever`.

What do you expect in this field? If it is simple semver then you should account for an extra optional digit, e.g. `"^[a-zA-Z0-9]+\\.[a-zA-Z0-9]+(\\.[a-zA-Z0-9]+)?`. More complex semver regex is provided at [semver.org](https://semver.org/) which I believe would be this one:

https://regex101.com/r/vkijKf/1/

**Comment by goneall** [comment]
OK - I think I know the issue.  We changed the format of the version string with SPDX spec version 3.0 to include a patch version and the library is still checking the old format.

We should update the check to allow both formats.  We probably updated the license list with the new version which is causing the issue.

I'll see if I can get a fix and patch release out to fix this.

**Comment by garydgregory** [comment]
> Thanks @garydgregory for the analysis - is the issue that the string in the license list version contains extra characters (e.g. spaces)? If so, perhaps we can fix this in the spdx-maven-plugin by trimming the string.
> 
> From a strict spec perspective, the license list version field should match precisely.

Note that it's @aherbert that performed the analysis. I wanted to confirm that I see the issue whenever I build one of our 20+ Apache Commons jar files.

**Comment by goneall** [comment]
Thanks @aherbert for reporting the issue - I'll work on a PR.

**Comment by garydgregory** [comment]
Hi @goneall 
When can we expect a matching `spdx-maven-plugin`?
TY!

**Comment by goneall** [comment]
@garydgregory - Just published it - it should be available on Maven Central soon

**Comment by garydgregory** [comment]
TY @goneall !😀
