### ISSUE TITLE
License matching should ignore typical comment characters

### ISSUE THREAD

**Issue by goneall** [spdx/Spdx-Java-Library#29]
As per the License [Matching Guidelines section 6](https://spdx.github.io/spdx-spec/appendix-II-license-matching-guidelines-and-templates/#6-code-comment-indicators), comment characters should be ignored when matching licenses.

Currently, comment characters are not ignored in the license matching algorithm.

**Comment by goneall** [comment]
The following comment character should be ignored:

- `//` 
- `/*`
-`*/`
- 0 or more spaces followed by `*` at the start of the line (e.g. `^\s*\*`)
- `#` at the start of a line
- `'` at the start of a line
- `REM` at the start of a line
- `<!--`
- `-->`

Note: This list does not include the comments for COBOL, FORTRAN or DTD's.

**Comment by rkosinski941** [comment]
Hi Gary,

We also see Assembly language which has comments that start with ";".
We're also seeing Haskell now too which has "--" as the comment, but you can also do block comments with "{- -}"

We see PASCAL as well that has "(* *)" as block comments but I don't know if I've actually seen any PASCAL with commenting blocks.

**Comment by goneall** [comment]
I'll add the Assembly language, Haskell and PASCAL comments to the list.

Thinking about it a bit more, all single line comments and start block comments should only be preceded by white space within a single line.  Similarly, the end block comment will only be followed by white space - otherwise code would be included in the text to be matched.

I'll implement this by matching a regular expression with the above assumption - this will limit ignoring punctuation that should not be ignored per the matching guidelines.

**Comment by goneall** [comment]
After looking at the code, it looks like there has been some implementation of comment handling.  However, it does not work for the regular expression rules since the regular expression is compared to the original text which contains the comments.

To solve this, we should remove the comment strings from the "original text".

**Comment by goneall** [comment]
@rkosinski941 I'm going to spin another release over the next couple of days.  If you have any license text we can include as unit tests, attach here and I'll try to make the license matcher work for those cases before the release.

**Comment by goneall** [comment]
Resolved with PR #30
