### ISSUE TITLE
SPDX Object Model diagram link in README is dead

### ISSUE THREAD

**Issue by rpavlik** [spdx/Spdx-Java-Library#35]
Is this the substitute? https://github.com/spdx/spdx-spec/blob/development/v2.2.1/model/SPDX-UML-Class-Diagram.jpg

You might want to actually link to a specific revision so it won't break again, which would be https://github.com/spdx/spdx-spec/blob/2a7aff7afa089a774916bd5c64fc2cb83637ea07/model/SPDX-UML-Class-Diagram.jpg

**Comment by goneall** [comment]
Thanks @rpavlik for pointing this out.

Resolved with PR #36
