### ISSUE TITLE
Performance Optimization Enhancement for Verification

### ISSUE THREAD

**Issue by goneall** [spdx/Spdx-Java-Library#57]
One way to speed up the verification algorithm is to cache the results of each element being verified.  It will take up more memory, but save having to re-parse and traverse the graph for elements if they are referenced more than once (e.g. within a relationship).

**Comment by puerco** [comment]
Thanks a lot @goneall I'll give it a go when you cut a new release!

**Comment by goneall** [comment]
@puerco I'll be cutting a new release within the next few days - quite a few people have run into this performance issue, so it would be nice to get out a fix especially for the online tools.

**Comment by goneall** [comment]
Resolved with PR #56

**Comment by goneall** [comment]
@puerco I just released [version 1.0.2 of the SPDX Tools Java](https://github.com/spdx/tools-java/releases/tag/v1.0.2) which includes a fix for this issue.  Let me know if this resolves the performance issue for you.  If it does resolve the issue, would you mind updating the twitter message with the improved results?

**Comment by puerco** [comment]
@goneall of course! Thank you very much for fixing this.
https://twitter.com/puerco/status/1416080001775112195

**Comment by goneall** [comment]
Thanks @puerco for the update.
