### ISSUE TITLE
groff(1) comment syntax is not supported

### ISSUE THREAD

**Issue by alejandro-colomar** [spdx/Spdx-Java-Library#63]
As reported in <https://github.com/spdx/license-list-XML/pull/1319>, the comment syntax of groff, and therefore that of the man-pages, isn't supported.

The implementation is here:

<https://github.com/spdx/Spdx-Java-Library/blob/e47801caeabb3148f75975279ba38ccd63260958/src/main/java/org/spdx/utility/compare/LicenseCompareHelper.java#L138>

groff comments basically start with `.\"`.  If I have some time, I'll try and fix it, but in the meantime I'll report it :)

**Comment by goneall** [comment]
@alejandro-colomar Can you point me to a a typical document with a license I can use for a test case?  I'm working on a new release of the library and may be able to get a fix in before the release.

**Comment by alejandro-colomar** [comment]
Yes, I'll look it up tomorrow.  Thanks!

**Comment by alejandro-colomar** [comment]
You can check it in your system:  At least on Debian, you can `zcat /usr/share/man/man2/membarrier.2.gz`

If you need to download it, you could either clone the man-pages repo and find `./man2/membarrier.2`, or you can download just that page from the kernel git repo: <https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/plain/man2/membarrier.2>

**Comment by goneall** [comment]
Thanks @alejandro-colomar - I copied the license text and used it for the unit test.
