### ISSUE TITLE
Where to put the vulnerabilities

### ISSUE THREAD

**Issue by zhaolida98** [spdx/Spdx-Java-Library#76]
Hi, I am wondering where to put the Vulnerabilities or CVE info for SBOM packages. In the official document, such reference should be put in [external reference](https://spdx.github.io/spdx-spec/external-repository-identifiers/#f2-security), but only two types are provided. None of them are suitable for CVE. However, the [example here](https://github.com/spdx/spdx-spec/blob/vulnerability-profile/examples/SPDXVulnerabilityJSONExample-v3.0.spdx.json) in  [this issue](https://github.com/spdx/spdx-spec/pull/510) provide a totally different solution, which has a huge gap between [the example](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXJSONExample-v2.2.spdx.json) we previously referred to. These examples make me confused. Which one is the real SPDX format? What is the true official format for vulnerability (CVE) information?

**Comment by goneall** [comment]
@zhaolida98 The [SPDX 3.0 vulnerability example](https://github.com/spdx/spdx-spec/blob/vulnerability-profile/examples/SPDXVulnerabilityJSONExample-v3.0.spdx.json) is for SPDX 3.0 which is a work in progress and not yet release.

There is a subgroup actively working on adding vulnerability information for an upcoming release of SPDX 2.3.  This issue tracks adding the vulnerability information:  https://github.com/spdx/spdx-spec/issues/627

I would encourage tracking and participating in this part of the spec to make sure the 2.3 release works for your usage.

For SPDX 2.2, I would suggest creating an ExternalRef with a type OTHER (e.g. `ExternalRef: OTHER cve XXX` where XXX is the CVE reference).

**Comment by goneall** [comment]
@zhaolida98 We are about to release version 2.3 which includes some additional vulnerability external reference types. 

See the [draft section on including security information](https://github.com/spdx/spdx-spec/blob/development/v2.3/chapters/how-to-use.md#g1-including-security-information-in-a-spdx-document).

Since the libraries are now updated with the 2.3 spec, I'll close this issue as resolved.
