### ISSUE TITLE
Convert throws "I/O error opening Json TOC URL"

### ISSUE THREAD

**Issue by sschuberth** [spdx/Spdx-Java-Library#79]
When trying to convert a tag-value document to YAML I get

```
java -jar tools-java-1.0.4-jar-with-dependencies.jar Convert doc.spdx doc.yaml
11:00:11.804 [main] ERROR org.spdx.storage.listedlicense.SpdxListedLicenseModelStore - I/O error opening Json TOC URL
```

Can this by due to the system proxy not being support? If so, would it maybe make sense to add proxy support e.g. via https://github.com/MarkusBernhardt/proxy-vole?

**Comment by goneall** [comment]
> I didn't see such a warning, and also no mention of success, which is why I didn't even bother to look for an output file... but now that I did, I see that the YAML output was indeed generated!

Definitely a different issue.  Maybe a classpath issue getting access to the resources files?

I do test this scenario on my local dev environment by running the unit tests disconnected from the internet - but I recall problems in the past which are classpath related.

> I wanted to, but I had trouble getting the project to build in IntelliJ IDEA. For some reason quite a few dependencies could not be found.

Interesting - You might try just the Java library and see if that builds.  Much much less dependencies.  I use Eclipse myself for the SPDX projects.

**Comment by goneall** [comment]
@sschuberth I'm working on a new release and started looking at using [proxy-vole](https://github.com/MarkusBernhardt/proxy-vole).  I'm concerned about the number of dependencies this library will bring in, especially delight-nashorn-sandbox.

I'll work on updating the logging so the messages are a bit more accurate, but at this point I'm thinking we don't add proxy support unless we can find a lighter weight dependency.  BTW - the number one concern I've heard from the previous version of the Java libraries is the large number of dependencies which are now moved to a separate project - tools-Java, so you can include the library without all the baggage.

**Comment by sschuberth** [comment]
> especially delight-nashorn-sandbox.

Yeah, that's probably for PAC file paring, which is might be overkill anyway.

**Comment by goneall** [comment]
I updated the error message to be more descriptive in PR #88 

`Unable to access the most current listed licenses from https://spdx.org/licenses - using locally cached licenses: [cause]`
